version: '3.8'
services:
  frontend:
    build:
      context: ./frontend/tealfleet
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    env_file: .env
    build:
      context: ./backend/tealfleet
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  ingress:
    build: 
      context: ./ingress
      dockerfile: Dockerfile
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config


volumes:
  postgres_data:
  caddy_data:
  caddy_config:

